apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase-lab
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_DBNAME
          value: "metabase"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: "metabase"
        - name: MB_DB_PASS
          value: "password"
        - name: MB_DB_HOST
          value: "postgres.metabase-lab.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase-lab
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001  # Define uma porta fixa para o serviço
  type: NodePort

